baseURL = "http://localhost:1313"
title = "orphicsec"
theme = "PaperMod"
languageCode = "en-us"

[pagination]
  pagerSize = 10

[params]
  env = "production"
  description = "Security research and exploits"
  author = "orphic"
  
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  
  defaultTheme = "dark"
  disableThemeToggle = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
