baseURL = "https://orphicsec.com"
theme = "PaperMod"
title = "orphic"
languageCode = "en-us"

[pagination]
  pagerSize = 10

[params]
  env = "production"
  description = "Security research and exploits"
  author = "orphic"
  
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  
  defaultTheme = "dark"
  disableThemeToggle = true

  [params.homeInfoParams]
      Title = ">$ orphic"
      Content = """
self-proclaimed security researcher

building and sometimes breaking things professionally
"""

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
